'use client'
import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './cssStyles/productsStyle.css'
import Header from './shoppingComponents/header';
import Footer from './shoppingComponents/footer';
import Product_div from './shoppingComponents/main';
import Aside from './shoppingComponents/aside';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const ShoppingLayout = ({ children }: { children: React.ReactNode }) => {
    return (
      <html lang="en">

        <Header/>

        <main className='product'>
              <article>

                <Product_div/>
                <Aside/>

              </article>
        </main>
     
        <Footer/>

      </html>
    );
  };
  
  export default ShoppingLayout;


